# AVD-US-PROJECT-01 shared attributes

# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."


# OOB Management network default gateway.
mgmt_gateway: 192.168.200.1

# dns servers.
name_servers:
 - 192.168.200.5
 - 8.8.8.8

dns_domain: avd-lab.local

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management
ntp_servers:
  - 0.north-america.pool.ntp.org
  - 1.north-america.pool.ntp.org