# DC1 Spine Switches

type: spine

spine:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65001
    uplink_ipv4_pool: 10.255.255.0/24
    loopback_ipv4_pool: 192.168.254.0/24
    bgp_defaults: ['no bgp default ipv4-unicast', 'distance bgp 20 200 200']
    max_uplink_switches: 3
  nodes:
    DC1-SPINE1:
      id: 1
      mgmt_ip: 192.168.200.101/24
      uplink_interfaces: ['Ethernet11', 'Ethernet12', 'Ethernet13']
      uplink_switches: ['DC1-SPINE2', 'DC1-SPINE3', 'DC1-SPINE4']
      uplink_switch_interfaces: [ 'Ethernet11', 'Ethernet11', 'Ethernet11']
    DC1-SPINE2:
      id: 2
      mgmt_ip: 192.168.200.102/24
      uplink_interfaces: ['Ethernet12', 'Ethernet13']
      uplink_switches: ['DC1-SPINE3', 'DC1-SPINE4']
      uplink_switch_interfaces: [ 'Ethernet12', 'Ethernet12']
    DC1-SPINE3:
      id: 3
      mgmt_ip: 192.168.200.103/24
      uplink_interfaces: ['Ethernet13']
      uplink_switches: ['DC1-SPINE4']
      uplink_switch_interfaces: ['Ethernet13']
    DC1-SPINE4:
      id: 4
      mgmt_ip: 192.168.200.104/24