# DC1 Leaf switches

type: leaf

# LEAF
leaf:
  defaults:
    uplink_ipv4_pool: 172.31.255.0/24
    loopback_ipv4_pool: 192.168.255.0/24
    uplink_interfaces: ['Ethernet1', 'Ethernet2', 'Ethernet3', 'Ethernet4']
    uplink_switches: ['DC1-SPINE1', 'DC1-SPINE2', 'DC1-SPINE3', 'DC1-SPINE4']
    bgp_defaults: ['no bgp default ipv4-unicast', 'distance bgp 20 200 200']
    platform: cEOS-LAB
  nodes:
    DC1-LEAF1:
      bgp_as: 65101
      id: 1
      mgmt_ip: 192.168.200.105/24
      uplink_switch_interfaces: [ Ethernet1, Ethernet1, Ethernet1, Ethernet1 ]
    DC1-LEAF2:
      bgp_as: 65102
      id: 2
      mgmt_ip: 192.168.200.106/24
      uplink_switch_interfaces: [ Ethernet2, Ethernet2, Ethernet2, Ethernet2 ]
    DC1-LEAF3:
      bgp_as: 65103
      id: 3
      mgmt_ip: 192.168.200.107/24
      uplink_switch_interfaces: [ Ethernet3, Ethernet3, Ethernet3, Ethernet3 ]
    DC1-LEAF4:
      bgp_as: 65104
      id: 4
      mgmt_ip: 192.168.200.108/24
      uplink_switch_interfaces: [ Ethernet4, Ethernet4, Ethernet4, Ethernet4 ]